spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods:
              - POST
              - GET
              - DELETE
              - PUT
        add-to-simple-url-handler-mapping: true


server:
  port: '8089'
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8090/eureka/'




