spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
        add-to-simple-url-handler-mapping: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin


server:
  port: '8089'
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8090/eureka/'




